export enum TECHNOLOGIES {
  RUBY = 'ruby',
  RUBY_ON_RAILS = 'ruby-on-rails',
  JAVASCRIPT = 'javascript',
  REACT = 'react',
  AWS_S3 = 's3',
  POSTGRESQL = 'postgresql',
  SQL = 'sql',
  PYTHON = 'python',
  DJANGO = 'django',
  MONGO = 'mongo',
  CLOUDFLARE = 'cloudflare',
  ANGULAR = 'angular',
  TYPESCRIPT = 'typescript',
  SASS = 'sass',
  D3 = 'd3',
  REDUX = 'redux',
  NODE = 'node',
  CSS3 = 'css3',
  HTML5 = 'html5',
  STYLUS = 'stylus',
}

export const TECHNOLOGIES_SRC_MAPPING: { [key: string]: string } = {
  [`${TECHNOLOGIES.RUBY}`]: 'assets/svg/ruby.svg',
  [`${TECHNOLOGIES.RUBY_ON_RAILS}`]: 'assets/svg/ruby-on-rails.svg',
  [`${TECHNOLOGIES.JAVASCRIPT}`]: 'assets/svg/javascript.svg',
  [`${TECHNOLOGIES.AWS_S3}`]: 'assets/svg/aws-s3.svg',
  [`${TECHNOLOGIES.POSTGRESQL}`]: 'assets/svg/postgresql.svg',
  [`${TECHNOLOGIES.SQL}`]: 'assets/svg/sql.svg',
  [`${TECHNOLOGIES.PYTHON}`]: 'assets/svg/python.svg',
  [`${TECHNOLOGIES.DJANGO}`]: 'assets/svg/django.svg',
  [`${TECHNOLOGIES.MONGO}`]: 'assets/svg/mongo.svg',
  [`${TECHNOLOGIES.CLOUDFLARE}`]: 'assets/svg/cloudflare.svg',
  [`${TECHNOLOGIES.ANGULAR}`]: 'assets/svg/angular.svg',
  [`${TECHNOLOGIES.TYPESCRIPT}`]: 'assets/svg/typescript.svg',
  [`${TECHNOLOGIES.SASS}`]: 'assets/svg/sass.svg',
  [`${TECHNOLOGIES.D3}`]: 'assets/svg/d3.svg',
  [`${TECHNOLOGIES.REDUX}`]: 'assets/svg/redux.svg',
  [`${TECHNOLOGIES.NODE}`]: 'assets/svg/node.svg',
  [`${TECHNOLOGIES.CSS3}`]: 'assets/svg/css3.svg',
  [`${TECHNOLOGIES.HTML5}`]: 'assets/svg/html5.svg',
  [`${TECHNOLOGIES.STYLUS}`]: 'assets/svg/stylus.svg',
};
